### ISSUE TITLE
Giving Ben Permission on Fire-base DB

### ISSUE THREAD

**Issue by Benkia** [naveh92/GroceryAndroid#20]
Hi mister can you give me permission to the DB Please !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@naveh92 
#DB #Haapy #Navah

**Comment by naveh92** [comment]
a-wut-wut b0i,
there are n0 permissionz in teh DB

**Comment by Benkia** [comment]
https://stackoverflow.com/questions/37569460/how-to-add-collaborators-to-a-firebase-app

**Comment by Benkia** [comment]
Thanks Mannnnnnnnnnnnnnnnnnnnnnnnnnnnnn 
#TheGever

**Comment by naveh92** [comment]
You are a big hnoon
#NoProblemz
