### ISSUE TITLE
Why do we need to send DatabaseHelper.getInstance().getWritableDatabase() every time? Can't we just do it in a function of an abstract class which all Tables extend?

### ISSUE THREAD

**Issue by naveh92** [naveh92/GroceryAndroid#25]

**Comment by naveh92** [comment]
Ben check commit 9442dd4 (from July 21) and make sure it's ok according to Eliav:

Created an abstract class that holds the static reference for writableDB and readableDB.
Now, instead of sending the Readable/Writable DB to the Table classes, we already have them.

**Comment by Benkia** [comment]
Looks good
