### ISSUE TITLE
BUG or Feature - Leaving a group don't update the lists tab

### ISSUE THREAD

**Issue by Benkia** [naveh92/GroceryAndroid#30]
If you have 2 phones with the same user
On one phone you leave the group 
And on the anther one you still has the group

**Comment by naveh92** [comment]
What activity/fragment/model? lists tab or group members or just user groups?

**Comment by naveh92** [comment]
Lists tab: 
You can leave a group only actively (No one can kick you out), so Lists tab is updated only when you leave a group..

User groups tab:
It does update, I checked it (Shouldn't really, for the same reason).

Group members tab:
We fetch from local, so we can't observe the remote.. Kind of bug but doesn't really matter too much.

If you meant something else call me homie
