### ISSUE TITLE
LocalDb

### ISSUE THREAD

**Issue by naveh92** [naveh92/GroceryAndroid#4]

**Comment by Benkia** [comment]
What did you mean by [LastUpdateTable ](https://github.com/naveh92/GroceryAndroid/blob/master/app/src/main/java/com/example/admin/myapplication/controller/database/remote/UserGroupsDB.java#L48)
To add LastUpdateTable in LocalDB or just get the timestamp in the table

**Comment by naveh92** [comment]
What's left: 
1) UserGroceryListsModel - Done, but we don't save any Lists to the local storage, because we can't use them:
Firebase doesn't allow a query with 2 filters (We filter using the groupKey, to get all the lists in a group), so we can't filter according to lastUpdatedTime..
Currently just fetch all GroceryList records from remote 100% of the time.
